# Generated by Django 4.1.1 on 2023-05-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_alter_mapview_options_alter_response_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='respondent',
        ),
    ]
