# Generated by Django 4.1.1 on 2023-05-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_mapview_geojson'),
        ('apiapp', '0008_remove_response_respondent'),
    ]

    operations = [
    ]
