# Generated by Django 4.1.1 on 2023-05-24 10:33

import apiapp.models.mapview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_merge_20230524_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapview',
            name='map_service_url',
            field=models.CharField(default=apiapp.models.mapview.default_service_url, max_length=150, verbose_name='Map Service URL'),
        ),
        migrations.AlterField(
            model_name='mapview',
            name='options',
            field=models.JSONField(default=apiapp.models.mapview.default_options),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
